### PR TITLE
added context pointer to trace callback

### PR DESCRIPTION
**Pull request by jpihl**

### CODE REVIEW

**Comment by jpihl** [comment]
This is especially helpful in kodo-cpp as it allows the use of a std::function or a "context-having" lambda instead of a pure c function pointer.

Any comments @mortenvp

**Comment by mortenvp** [comment]
Yes, I have comments.. should we not add this in kodo directly first? I don't think it is a good idea that the bindings change the API. They should be pure forwarders

**Comment by jpihl** [comment]
No kodo already uses std::function for the callback. It's because pure c function pointers have a huge drawback if they don't include a context pointer.

**Comment by mortenvp** [comment]
That makes sense. We just need to document that carefully. It's not good if the APIs drift.

**Comment by mortenvp** [comment]
Lets add to the docs why the context pointer is useful and that is added to the API here because Kodo does not require it due to its use of std::function

**Comment by jpihl** [comment]
where should i add this exactly?

**Comment by mortenvp** [comment]
I would say here: https://github.com/steinwurf/kodo-c/blob/master/src/kodoc/kodoc.h#L536-L543

A bit more explanation + maybe even an example would not hurt I think. 

I would also add the `context` to the signature:
```
void kodo_set_trace_callback(kodo_coder_t coder, kodo_trace_callback_t callback,
    void* context);
```

**Comment by jpihl** [comment]
ah missed that - i'll do it rightway..

**Comment by jpihl** [comment]
I've added a new pull request: https://github.com/steinwurf/kodo-c/pull/40

**Pull request merged**
