### PR TITLE
run multiple times

### PR DESCRIPTION
**Pull request by jpihl**
@petya2164 any comments?

### CODE REVIEW

**Comment by petya2164** [comment]
@jpihl Let's take a step back and simplify this by invoking run_coding_test multiple times.

**Comment by mortenvp** [comment]
Why not just use gauge for this?

**Comment by jpihl** [comment]
Using gauge for this seems like a good approach. It seemed like the intention for this benchmark was to keep it simple and maybe even C?
But it's really nice to have so I think we should try to improve it somehow.

**Comment by petya2164** [comment]
Indeed, this was intended to be a C benchmark, this is kodo-c after all! I only added C++ elements to get an accurate timer, but those can be replaced with some platform-specific function calls.
I think that the simplicity will be lost if we bring in gauge :(

**Comment by mortenvp** [comment]
Depends on how you look at it.. In my opinion: if it is a benchmark then use gauge - if it is an example of how to use kodo-c then write it in C.

**Pull request closed without merging**
