### PR TITLE
added an explaination for the trace callback's context

### PR DESCRIPTION
**Pull request by jpihl**

### CODE REVIEW

**Comment by jpihl** [comment]
@mortenvp is this explanation sufficient?

**Comment by mortenvp** [comment]
I would add a reference to the type of the callback function and explain that the trace callback will pass whatever the user provided back to the user on each callback event.

**Comment by jpihl** [comment]
@mortenvp better?

**Comment by jpihl** [comment]
Otherwise could you write something you think makes sense? I'm not that fond of guessing games.. :)

**Comment by mortenvp** [comment]
Perhaps something like that. When you do something like that, would somebody else be able to understand what it does and what is the purpose. For example ask @nestorjhernandezm whether he understands the purpose of the context pointer.

**Comment by jpihl** [comment]
@mortenvp I bet you love it now!

**Comment by mortenvp** [comment]
Awesome comment! Love it now.

**Comment by nestorjhernandezm** [comment]
I love it :smile:

**Pull request merged**
